# fly.toml app configuration file generated for tsoha-harjoitustyo on 2024-04-07T22:42:21+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tsoha-harjoitustyo'
primary_region = 'arn'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '5000'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
